
let s:config_home = exists('$XDG_CONFIG_HOME') ? $XDG_CONFIG_HOME : expand('~/.config')
let s:state_home = exists('$XDG_STATE_HOME') ? $XDG_STATE_HOME : expand('~/.local/state')

:call system('mkdir $s:state_home/vim/swap')
:call system('mkdir $s:state_home/vim/undo')

set viminfo+=n$s:config_home/vim/viminfo
set directory=$s:state_home/vim/swap
set undodir=$s:state_home/vim/undo

source $s:config_home/vim/option.vim
