#!/usr/bin/bash

# Environment Variables

## XDG
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

## devenv
export BREW_PREFIX="$XDG_DATA_HOME/brew"
export EDITOR=nvim
export PIPENV_VENV_IN_PROJECT=1
export PYENV_ROOT="$HOME/.pyenv"
export RYE_HOME="$XDG_DATA_HOME/rye"
export SVLINT_CONFIG="$HOME/.config/svls/.svlint.toml"
export VOLTA_HOME="$XDG_DATA_HOME/volta"

export HISTFILE="$HOME/.local/share/shell/history"
export HISTSIZE=10000
export SAVEHIST=10000

array=(
    "/usr/bin/lesspipe"
    "/usr/bin/lesspipe.sh"
)

for item in "${array[@]}"; do
    if [ -e "$item" ]; then
        export LESSOPEN="|$item %s"
        export LESSCLOSE="$item %s %s"
    fi
done

#PATH

## Devtools

array=(
    "$HOME/bin"
    "$HOME/.local/bin"
    "$HOME/go/bin"
    "$PYENV_ROOT/bin"
    "$HOME/.cargo/bin"
    "$VOLTA_HOME/bin"
    "$RYE_HOME/shims"
)

for item in "${array[@]}"; do
    export PATH="$item:$PATH"
done

array=(
    "$HOME/.nix-profile/etc/profile.d/nix.sh"
    "/nix/var/nix/profiles/default/etc/profile.d/nix.sh"
)

for item in "${array[@]}"; do
    if [ -e "$item" ]; then
        #shellcheck source=/dev/null
        source "$item"
    fi
done
