#!/usr/bin/bash

# Environment Variables

## XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.local/cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

## Use XDG
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/credentials"
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"
export BREW_PREFIX="$XDG_DATA_HOME/brew"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CONDARC="$XDG_CONFIG_HOME/conda/condarc"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export DENO_INSTALL="$XDG_DATA_HOME/deno"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export DOTNET_CLI_HOME="$XDG_DATA_HOME/dotnet"
export GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export GOPATH="$XDG_DATA_HOME/go"
export LESSHISTFILE="$XDG_STATE_HOME/less/history"
export LIMA_HOME="$XDG_DATA_HOME/lima"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PLATFORMIO_CORE_DIR="$XDG_DATA_HOME/platformio"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export RYE_HOME="$XDG_DATA_HOME/rye"
export VOLTA_HOME="$XDG_DATA_HOME/volta"
export XCURSOR_PATH="/usr/share/icons:$XDG_DATA_HOME/icons"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# devenv
export SVLINT_CONFIG="$HOME/.config/svls/.svlint.toml"
export EDITOR=nvim
export PIPENV_VENV_IN_PROJECT=1

export HISTFILE="$HOME/.local/share/shell/history"
export HISTSIZE=10000
export SAVEHIST=10000

array=(
    "/usr/bin/lesspipe"
    "/usr/bin/lesspipe.sh"
)

for item in "${array[@]}"; do
    if [ -e "$item" ]; then
        export LESSOPEN="|$item %s"
        export LESSCLOSE="$item %s %s"
    fi
done

#PATH

## Devtools

array=(
    "$HOME/bin"
    "$HOME/.local/bin"
    "$GOPATH/bin"
    "$PYENV_ROOT/bin"
    "$CARGO_HOME/bin"
    "$VOLTA_HOME/bin"
    "$RYE_HOME/shims"
    "$DENO_INSTALL/bin"
    "$XDG_STATE_HOME/nix/profiles/profile/bin"
)

for item in "${array[@]}"; do
    export PATH="$item:$PATH"
done

# array=(
# )

# for item in "${array[@]}"; do
#     if [ -e "$item" ]; then
#         #shellcheck source=/dev/null
#         source "$item"
#     fi
# done
