["zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"

["zsh-completions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-completions.git"
    refreshPeriod = "168h"

["zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"

["powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"
    ["powerlevel10k".clone]
        args = [ "--depth", "1" ]
