name: 'Setup Dotfiles'
description: 'Install chezmoi and initialize dotfiles'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install chezmoi
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          mkdir -p "$HOME/.local/bin"
          curl -L "https://github.com/twpayne/chezmoi/releases/latest/download/chezmoi-windows-amd64.exe" -o "$HOME/.local/bin/chezmoi.exe"
        else
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin"
        fi

    - name: Initialize dotfiles
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          # Use powershell for Windows-specific setup
          powershell.exe -Command "& '$HOME\.local\bin\chezmoi.exe' init --apply --promptDefaults -S . ; \$Env:PATH=\"\$HOME\scoop\shims;\$Env:PATH\" ; . \"\$HOME\Documents\PowerShell\Microsoft.PowerShell_profile.ps1\" ; Install-Scoop"
        else
          "$HOME/.local/bin/chezmoi" init --apply --promptDefaults -S .
        fi
