[settings]
experimental = true
install_before = "3d"

[tools]
deno = "latest"
node = "lts"
usage = "latest"
uv = "latest"
pnpm = "latest"

# GitHub based tools (including those to be migrated to native package managers)
"github:708u/twig" = "latest"
"github:bahdotsh/wrkflw" = "latest"
"github:coder3101/protols" = "latest"
"github:cordx56/rustowl" = "latest"
"github:terror/just-lsp" = "latest"
"github:trasta298/keifu" = "latest"

# Node.js based tools
"npm:@biomejs/biome" = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:basedpyright" = "latest"
"npm:bash-language-server" = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:neovim" = "latest"
"npm:opencode-ai" = "latest"
"npm:pyright" = "latest"
"npm:semver" = "latest"
"npm:svelte-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"npm:yaml-language-server" = "latest"

# Python based tools
"pipx:black" = "latest"
"pipx:cmake-language-server" = "latest"
"pipx:flake8" = "latest"
"pipx:ignr" = "latest"
"pipx:isort" = "latest"
"pipx:mypy" = "latest"
"pipx:ruff" = "latest"
"pipx:yt-dlp" = "latest"
