[settings]
experimental = true

[tools]
deno = "latest"
node = "lts"
usage = "latest"
uv = "latest"

# GitHub based tools (including those to be migrated to native package managers)
"github:708u/twig" = "latest"
"github:coder3101/protols" = "latest"
"github:cordx56/rustowl" = "latest"
"github:docker/docker-language-server" = "latest"
"github:jFryy/systemd-lsp" = "latest"
"github:jtroo/kanata" = "latest"
"github:terror/just-lsp" = "latest"
"github:trasta298/keifu" = "latest"
"github:arduino/arduino-language-server" = "latest"
"github:artempyanykh/marksman" = "latest"
"github:bahdotsh/wrkflw" = { version = "latest", os = ["darwin", "linux"] }
"github:BurntSushi/ripgrep" = "latest"
"github:cli/cli" = "latest"
"github:cloudflare/cloudflared" = "latest"
"github:jesseduffield/lazydocker" = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:jqlang/jq" = "latest"
"github:junegunn/fzf" = "latest"
"github:LuaLS/lua-language-server" = "latest"
"github:nektos/act" = "latest"
"github:neovim/neovim" = "latest"
"github:rhysd/actionlint" = "latest"
"github:sharkdp/bat" = "latest"
"github:sharkdp/fd" = "latest"
"github:sxyazi/yazi" = "latest"
"github:tombi-toml/tombi" = "latest"
"github:twpayne/chezmoi" = "latest"
"github:ynqa/jnv" = "latest"
"github:arduino/arduino-cli" = "latest"
"github:dandavison/delta" = "latest"
"github:eza-community/eza" = "latest"
"github:casey/just" = "latest"
"github:pnpm/pnpm" = "latest"
"github:mozilla/sccache" = "latest"
"github:koalaman/shellcheck" = "latest"
"github:mvdan/sh" = "latest"
"github:starship/starship" = "latest"
"github:JohnnyMorganz/StyLua" = "latest"
"github:tree-sitter/tree-sitter" = "latest"
"github:ajeetdsouza/zoxide" = "latest"

# Gitlab based tools
"gitlab:gitlab-org/cli" = "latest"

# Node.js based tools
"npm:@biomejs/biome" = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:basedpyright" = "latest"
"npm:bash-language-server" = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:neovim" = "latest"
"npm:opencode-ai" = "latest"
"npm:pyright" = "latest"
"npm:semver" = "latest"
"npm:svelte-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"npm:yaml-language-server" = "latest"

# Python based tools
"pipx:black" = "latest"
"pipx:cmake-language-server" = "latest"
"pipx:flake8" = "latest"
"pipx:ignr" = "latest"
"pipx:isort" = "latest"
"pipx:mypy" = "latest"
"pipx:ruff" = "latest"
"pipx:yt-dlp" = "latest"
