[data]
    # starship oh-my-posh"
    powershell = "starship"
    # starship oh-my-posh
    bash = "starship"
    # starship oh-my-posh powerlevel10k
    zsh = "powerlevel10k"

    servers = ["anko", "baz", "dn", "dockernode", "tippy", "share"]
