[option]
exclude_paths = []
textwidth = 120
copyright_linenum = 1
copyright_year = "1234"
copyright_holder = "HOLDER"
indent = 2
prefix_inout = "b_"
prefix_input = "i_"
prefix_output = "o_"
prefix_label = "l_"
prefix_instance = "u_"
prefix_module = "mod_"
prefix_package = "pkg_"
prefix_interface = "ifc_"
re_required_assert = "^[a-z]+[a-z0-9_]*$"
re_required_assert_property = "^[a-z]+[a-z0-9_]*$"
re_required_checker = "^[a-z]+[a-z0-9_]*$"
re_required_class = "^[a-z]+[a-z0-9_]*$"
re_required_function = "^[a-z]+[a-z0-9_]*$"
re_required_generateblock = "^[a-z]+[a-z0-9_]*$"
re_required_genvar = "^[a-z]+[a-z0-9_]*$"
re_required_instance = "^[a-z]+[a-z0-9_]*$"
re_required_interface = "^[a-z]+[a-z0-9_]*$"
re_required_localparam = "^[A-Z]+[A-Z0-9_]*$"
re_required_modport = "^[a-z]+[a-z0-9_]*$"
re_required_module_ansi = "^[a-z]+[a-zA-Z0-9_]*$"
re_required_module_nonansi = "^[A-Z]+[A-Z0-9_]*$"
re_required_package = "^[a-z]+[a-z0-9_]*$"
re_required_parameter = "^[A-Z]+[A-Z0-9_]*$"
re_required_port_inout = "^[a-z]+[a-z0-9_]*$"
re_required_port_input = "^[a-z]+[a-z0-9_]*$"
re_required_port_output = "^[a-z]+[a-z0-9_]*$"
re_required_port_ref = "^[a-z]+[a-z0-9_]*$"
re_required_port_interface = "^[a-z]+[a-z0-9_]*$"
re_required_program = "^[a-z]+[a-z0-9_]*$"
re_required_property = "^[a-z]+[a-z0-9_]*$"
re_required_sequence = "^[a-z]+[a-z0-9_]*$"
re_required_task = "^[a-z]+[a-z0-9_]*$"
re_required_var_class = "^[a-z]+[a-z0-9_]*$"
re_required_var_classmethod = "^[a-z]+[a-z0-9_]*$"


[textrules]
header_copyright = false
style_textwidth = true

[syntaxrules]
action_block_with_side_effect = true
blocking_assignment_in_always_ff = true
blocking_assignment_in_always_latch = true
case_default = true
default_nettype_none = true
enum_with_type = true
eventlist_comma_always_ff = true
explicit_case_default = true

function_same_as_system_function = true
function_with_automatic = true
generate_case_with_label = true
generate_if_with_label = true

genvar_declaration_out_loop = true
inout_with_tri = true
interface_port_with_modport = true
keyword_forbidden_always = true

keyword_forbidden_priority = true
keyword_forbidden_unique = true
keyword_forbidden_unique0 = true
keyword_forbidden_wire_reg = true
keyword_required_generate = true

localparam_explicit_type = true
localparam_type_twostate = true
loop_statement_in_always_comb = true
loop_statement_in_always_ff = true
loop_statement_in_always_latch = true
loop_variable_declaration = true
lowercamelcase_interface = true
lowercamelcase_module = true
lowercamelcase_package = true
multiline_for_begin = true
multiline_if_begin = true

non_blocking_assignment_in_always_comb = true
operator_case_equality = true

parameter_default_value = true
parameter_explicit_type = true
parameter_in_generate = true
parameter_in_package = true
parameter_type_twostate = true
prefix_inout = false
prefix_input = false
prefix_instance = false
prefix_interface = false
prefix_module = false
prefix_output = false
prefix_package = false

re_required_assert = true
re_required_assert_property = true
re_required_checker = true
re_required_class = true
re_required_function = true
re_required_generateblock = true
re_required_genvar = true
re_required_instance = true
re_required_interface = true
re_required_localparam = true
re_required_modport = true
re_required_module_ansi = true
re_required_module_nonansi = true
re_required_package = true
re_required_parameter = true
re_required_port_inout = true
re_required_port_input = true
re_required_port_interface = true
re_required_port_output = true
re_required_port_ref = true
re_required_program = true
re_required_property = true
re_required_sequence = true
re_required_task = true
re_required_var_class = true
re_required_var_classmethod = true

style_indent = true
style_keyword_0or1space = true
style_keyword_0space = true
style_keyword_1or2space = true
style_keyword_construct = true
style_keyword_datatype = true
style_keyword_end = true

style_keyword_new = true
style_keyword_newline = true
style_operator_arithmetic = true
style_operator_boolean = true
style_operator_boolean_leading_space = true
style_operator_integer = true
style_operator_integer_leading_space = true
style_operator_unary = true
style_trailingwhitespace = true
tab_character = true
