#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2.0


[palette]
  powerline = "#444444"
  # separator = "#00ff00"
  separator = "#868686"
  text = "#ffffff"
  accent = "#98c379"


[[blocks]]
  alignment = "left"
  type = "prompt"

  [[blocks.segments]]
    background = "p:powerline"
    foreground = "p:text"
    style = "plain"
    type = "os"
    template = """ \
    {{ .Icon }}  \
    <p:separator>\ue0b1</>\
    """

    [blocks.segments.properties]
    windows = "<cyan>\uE62A</>"

  [[blocks.segments]]
    type = "path"
    background = "p:powerline"
    foreground = "p:text"
    style = "plain"
    powerline_symbol = "<p:separator>\ue0b1</>"
    # template = " {{ .Path }} "
    template = """ \
    <#009CD1>{{ .Parent }}</><green>{{ .Path }}</> \
    <p:separator>\ue0b1</>\
    """

    [blocks.segments.properties]
      folder_separator_icon = "/"
      # style = "full"
      style = "folder"

  [[blocks.segments]]
    type = "git"
    style= "plain"
    # style = "powerline"
    powerline_symbol = "<p:separator>\ue0b1</>"
    background = "p:powerline"
    foreground = "p:text"
    template = """ \
    {{ .UpstreamIcon }}{{ .HEAD }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}\
    {{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}\
    {{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }} \
    <p:separator>\ue0b1</>\
    """
    [blocks.segments.properties]
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = "python"
    style = "plain"
    powerline_symbol = "<p:separator>\ue0b1</>"
    background = "p:powerline"
    foreground = "p:text"
    display_mode = "files"
    template = """ \
    \ue73c {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}\
    <p:separator>\ue0b1</>
    """

  [[blocks.segments]]
    type = "executiontime"
    background = "p:powerline"
    foreground = "p:text"
    style = "plain"
    # powerline_symbol = "<p:separator>\ue0b1</>"

    template = """ \
    {{ .FormattedMs }} \
    <p:separator>\ue0b1</>
    """

    [blocks.segments.properties]
      always_enabled = false
      style = "austin"
      threshold = 10.0

  [[blocks.segments]]
    background = "transparent"
    foreground = "p:powerline"
    style = "plain"
    template = "\ue0b0"
    type = "text"

[[blocks]]
  alignment = "right"
  type = "prompt"

  [[blocks.segments]]
    background = "transparent"
    foreground = "p:powerline"
    style = "plain"
    template = "\ue0b2"
    type = "text"

  [[blocks.segments]]
    type = "kubectl"
    style = "plain"
    background = "p:powerline"
    foreground = "p:text"
    template = " ﴱ {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} "

    [properties.context_aliases]
    "arn:aws:eks:eu-west-1:1234567890:cluster/posh" = "posh"

  [[blocks.segments]]
    background = "p:powerline"
    foreground = "p:text"
    leading_diamond = "\ue0b2"
    style = "plain"
    type = "session"
    template = """ \
    {{ .UserName }}@{{ .HostName }} \
    <p:separator>\ue0b3</>\
    """

  [[blocks.segments]]
    background = "p:powerline"
    foreground = "p:text"
    style = "plain"
    type = "time"
    template = """ \
    {{ .CurrentDate | date .Format }} \uf017 \
    """

    [blocks.segments.properties]
      time_format = "15:04:05"

[[blocks]]
  alignment = "left"
  newline = true
  type = "prompt"

  [[blocks.segments]]
    background = "transparent"
    foreground = "p:accent"
    foreground_templates = ["{{ if gt .Code 0 }}#FF5252{{ end }}"]
    style = "plain"
    template = "❯ "
    type = "text"
    [blocks.segments.properties]
      always_enabled = true

[profiles]
  [profiles.defaults]

  [[profiles.list]]
    cursorShape = "bar"

[transient_prompt]
  # background = "transparent"
  # foreground = "#D4E157"
  template = "❯ "
