on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/**.yml"

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
