on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.toml"

jobs:
  toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2

      - uses: tombi-toml/setup-tombi@v1

      - name: Do Check
        run: |
          task check_toml
