name: Test chezmoi setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  on_posix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install chezmoi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin"

      - name: Initialize dotfiles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          "$HOME/.local/bin/chezmoi" init --apply --promptDefaults -S .

      - name: Apply dotfiles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          "$HOME/.local/bin/chezmoi" apply -k

  on_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Cache Scoop
        id: cache-primes
        uses: actions/cache@v5
        with:
          path: ~/scoop/cache
          key: scoop-cache

      - name: Install chezmoi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          New-Item -ItemType Directory -Force $HOME/.local/bin
          Invoke-WebRequest -Uri "https://github.com/twpayne/chezmoi/releases/latest/download/chezmoi-windows-amd64.exe" -OutFile $HOME/.local/bin/chezmoi.exe

      - name: Initialize dotfiles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          ."$HOME/.local/bin/chezmoi.exe" init --apply --promptDefaults -S .

      - name: Apply dotfiles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ."$HOME/.local/bin/chezmoi.exe" apply -k

      - name: Install Dependencies
        run: |
          $Env:PATH="$HOME\.local\bin;$Env:PATH"
          "$HOME\.local\bin" >> $Env:GITHUB_PATH
          $Env:PATH="$HOME\scoop\shims;$Env:PATH"
          "$HOME\scoop\shims" >> $Env:GITHUB_PATH
          . "$HOME\Documents\PowerShell\Microsoft.PowerShell_profile.ps1"
          scoop bucket add extras
          scoop bucket add versions
          scoop update
          # Install individually to prevent one failure from stopping everything
          Install-Scoop-Tools
          Install-Scoop-Dev-Tools
          try { Install-Scoop-GUI-Tools } catch { Write-Warning "GUI tools installation failed" }
