name: Test chezmoi setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CHEZMOI_SOURCE_DIR: ${{ github.workspace }}

jobs:
  on_posix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install chezmoi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $binDir = "$HOME/.local/bin"
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$binDir"
          echo "$binDir" >> "$GITHUB_PATH"

      - name: Initialize dotfiles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: chezmoi init --apply --promptDefaults

      - name: Apply dotfiles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: chezmoi apply -k

  on_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Cache Scoop
        id: cache-primes
        uses: actions/cache@v5
        with:
          path: ~/scoop
          key: scoop-cache

      - name: Install chezmoi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $binDir = Join-Path $HOME ".local" "bin"
          New-Item -ItemType Directory -Force $binDir
          Invoke-WebRequest -Uri "https://github.com/twpayne/chezmoi/releases/latest/download/chezmoi-windows-amd64.exe" -OutFile (Join-Path $binDir "chezmoi.exe")
          Add-Content $env:GITHUB_PATH $binDir

      - name: Initialize dotfiles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: chezmoi init --apply --promptDefaults

      - name: Apply dotfiles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chezmoi apply -k
          Add-Content $env:GITHUB_PATH (Join-Path $HOME "scoop" "shims")

      - name: Install Dependencies
        run: |
          scoop update
          Install-Scoop-Tools
          Install-Scoop-Dev-Tools
          Install-Scoop-GUI-Tools
