name: Test chezmoi setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install chezmoi
        run: |
          curl -sfL https://get.chezmoi.io | sh
          echo "$HOME/bin" >> "$GITHUB_PATH"

      - name: Run chezmoi init
        run: chezmoi init

      - name: Run chezmoi apply
        run: chezmoi apply -v
