name: Test chezmoi setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dotfiles
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
